### ISSUE TITLE
General Usage

### ISSUE THREAD

**Issue by dathinaios** [ntrocado/cl-markov-chains#1]
Hi there 😄

I would like to use this for music composition and was wondering if you could give me a quickstart example of basic usage. Assuming that I have a few functions, let's say `'(#'pattern1 #'pattern2 #'pattern3)` how would I go about defining the transition matrix? Also what does analyse do exactly?

Thanks!

**Comment by ntrocado** [comment]
Hi and thank you for your interest!

Typically the transition matrix is defined (automatically) by observing a chain of states. For example, if you have pattern1, then pattern2, then pattern1 again, then pattern3, etc., `analyze` will count how many times each pattern is followed by each of the others, and build the model with those values.

Example:

```lisp
(let* ((chain '(pat1 pat2 pat1 pat3 pat1 pat1 pat2 pat1 pat2 pat3 pat3 pat3 pat1 pat1))
       (model (analyze chain 1)))
  (generate model 50))
```
-> `(PAT1 PAT2 PAT3 PAT1 PAT3 PAT1 PAT2 PAT1 PAT1 PAT1 PAT2 PAT3 PAT1 PAT3 PAT3
 PAT1 PAT1 PAT1 PAT1 PAT1 PAT3 PAT3 PAT3 PAT3 PAT1 PAT1 PAT3 PAT3 PAT1 PAT1
 PAT2 PAT1 PAT1 PAT1 PAT1 PAT1 PAT3 PAT3 PAT1 PAT1 PAT2 PAT1 PAT2 PAT3 PAT3
 PAT1 PAT3 PAT1 PAT3 PAT1)`


If you want to directly establish the transition probabilities, I just added a function for that.
You must use a list in the form:
```
'((previous-state1 next-state1 probability1) 
  (previous-state2 next-state2 probability2) 
  ... 
  (previous-state-n next-state-n probability-n).
```

For example:
``` lisp
(let (model ((define-model '((pat1 pat1 0.4) (pat1 pat2 0.4) (pat1 pat3 0.2)
			     (pat2 pat1 0.5) (pat2 pat3 0.5)
			     (pat3 pat1 0.2) (pat3 pat3 0.8)))))
  (generate model 50))
```
-> `(PAT1 PAT1 PAT1 PAT2 PAT1 PAT3 PAT3 PAT3 PAT3 PAT3 PAT3 PAT3 PAT3 PAT3 PAT3
 PAT3 PAT3 PAT3 PAT3 PAT1 PAT1 PAT2 PAT1 PAT1 PAT1 PAT1 PAT1 PAT1 PAT1 PAT1
 PAT1 PAT3 PAT3 PAT3 PAT3 PAT3 PAT3 PAT3 PAT3 PAT3 PAT3 PAT3 PAT3 PAT1 PAT2
 PAT1 PAT1 PAT3 PAT3 PAT1)`

If pat1, pat2 and pat3 are functions, then it's a matter of, e.g., `funcall`ing  them, depending on what you are trying to achieve with the functions.

For example:
``` lisp
(mapcar (lambda (x) (funcall x args)) generated-results)
```

Let me know if this is clear enough.

**Comment by dathinaios** [comment]
Thanks! That is amazing 😄

I think I have enough with this to start fiddling.  Just one final question if you don't mind:

Looking at your `analyze` method make some think that it might be actually quicker to write down the patterns and let your function find them! Is there a way to get the result so that I can then use it to tweak further and use in the `define-model` function.
